# Generated by Django 4.2.3 on 2023-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('activity', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
