# Generated by Django 4.2.3 on 2023-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_uid_user_id_alter_user_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
