# Generated by Django 4.2.3 on 2023-07-28 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('07ee2ff6-9bfe-4a43-af25-2b6466d022ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
